import { describe, it } from 'node:test';
import * as assert from 'node:assert';
import { renderCLAUDEMD } from '../src/core/renderer';
import { RankedFact } from '../src/core/ranker';

describe('renderer', () => {
  it('output contains header', () => {
    const facts: RankedFact[] = [
      { text: 'typescript', sessionCount: 3, totalSessions: 5, confidence: 0.7, pattern: 'stack-mention', score: 0.6 },
    ];
    const output = renderCLAUDEMD(facts, 5);
    assert.ok(output.includes('# CLAUDE.md (generated by session-distill'));
  });

  it('stack facts go in ## stack section', () => {
    const facts: RankedFact[] = [
      { text: 'typescript', sessionCount: 3, totalSessions: 5, confidence: 0.7, pattern: 'stack-mention', score: 0.6 },
    ];
    const output = renderCLAUDEMD(facts, 5);
    assert.ok(output.includes('## stack'));
    assert.ok(output.includes('- typescript'));
  });

  it('every line has (seen in X/Y sessions)', () => {
    const facts: RankedFact[] = [
      { text: 'typescript', sessionCount: 3, totalSessions: 5, confidence: 0.7, pattern: 'stack-mention', score: 0.6 },
      { text: 'use git-ship for commits', sessionCount: 4, totalSessions: 5, confidence: 0.9, pattern: 'explicit-instruction', score: 0.8 },
    ];
    const output = renderCLAUDEMD(facts, 5);
    const factLines = output.split('\n').filter(l => l.startsWith('- '));
    for (const line of factLines) {
      assert.ok(/\(seen in \d+\/\d+ sessions\)/.test(line), `line missing seen count: ${line}`);
    }
  });

  it('empty sections are omitted', () => {
    const facts: RankedFact[] = [
      { text: 'typescript', sessionCount: 3, totalSessions: 5, confidence: 0.7, pattern: 'stack-mention', score: 0.6 },
    ];
    const output = renderCLAUDEMD(facts, 5);
    assert.ok(!output.includes('## workflow'));
    assert.ok(!output.includes('## preferences'));
    assert.ok(!output.includes('## context'));
  });
});
