import { RankedFact } from './ranker';

const WORKFLOW_KEYWORDS = /\b(deploy|commit|push|build|test|run|ship|ci|cd|pipeline)\b/i;

export function renderCLAUDEMD(facts: RankedFact[], totalSessions: number): string {
  const date = new Date().toISOString().split('T')[0];

  const stack: RankedFact[] = [];
  const workflow: RankedFact[] = [];
  const preferences: RankedFact[] = [];
  const context: RankedFact[] = [];

  for (const fact of facts) {
    if (fact.pattern === 'stack-mention') {
      stack.push(fact);
    } else if (
      (fact.pattern === 'convention' || fact.pattern === 'explicit-instruction') &&
      WORKFLOW_KEYWORDS.test(fact.text)
    ) {
      workflow.push(fact);
    } else if (fact.pattern === 'explicit-instruction' || fact.pattern === 'correction') {
      preferences.push(fact);
    } else {
      context.push(fact);
    }
  }

  const lines: string[] = [
    '# CLAUDE.md (generated by session-distill — review before using)',
    `# sessions analyzed: ${totalSessions} | generated: ${date}`,
  ];

  const sections: [string, RankedFact[]][] = [
    ['stack', stack],
    ['workflow', workflow],
    ['preferences', preferences],
    ['context', context],
  ];

  for (const [name, sectionFacts] of sections) {
    if (sectionFacts.length === 0) continue;
    lines.push('');
    lines.push(`## ${name}`);
    for (const fact of sectionFacts) {
      lines.push(`- ${fact.text} (seen in ${fact.sessionCount}/${fact.totalSessions} sessions)`);
    }
  }

  return lines.join('\n') + '\n';
}
